
---
AWSTemplateFormatVersion: 2010-09-09
Description: Cognito Application - Identity Pool

Parameters:
  IdentityPool:
    Type: String
    Description: Name of the identity pool

Resources:

   CognitoIdentityPool:
     Type: "AWS::Cognito::IdentityPool"
     Properties:
       IdentityPoolName: !Ref IdentityPool
       AllowUnauthenticatedIdentities: false
       CognitoIdentityProviders:
         - ClientId: !ImportValue cognito-user-pool-client-id
           ProviderName:
              !Join
                - ''
                - - "cognito-idp."
                  - !Ref AWS::Region
                  - ".amazonaws.com/"
                  - !ImportValue cognito-user-pool-id

Outputs:

  CognitoIdentityPool:
    Description: The id of the identity pool
    Value: !Ref CognitoIdentityPool
    Export:
      Name: cognito-identity-pool-id